#!/usr/bin/env bash
# SPDX-License-Identifier: ISC
#
# site/build.sh (vibe-61 / E8.4, I2b) — the SINGLE site build entry point.
#
# Local verification, site-validate, site-preview and deploy-site all build through this one
# script: site/data/ and site/reports/ are gitignored (D-D), so a clean checkout contains
# none of their output and no other path may invoke VitePress directly.
#
# The orchestrator runs the five bin/vibe-build-* tools into a TEMPORARY staging tree, then
# ATOMICALLY REPLACES the generated directories in --out with it. Replacement, not overwrite:
# a populated -> empty rebuild must leave no page from the previous build behind. It then
# renders dashboard.md and featured-audits.md unconditionally — an empty corpus is a state,
# not an error (D-C), and the empty site says so in as many words rather than reading broken.
#
# Usage: bash site/build.sh --corpus <dir> --out <dir> [--skip-vitepress]
# Exit:  0 built (empty corpus included) · 1 a builder or the VitePress build failed
#        · 2 usage error

set -euo pipefail

#: The exact notice an empty site carries, on every always-rendered page.
readonly EMPTY_NOTICE='no audit data yet'

#: The five builders of F10.3 / I1, each writing <out>/data/<slug>.json and its page.
readonly BUILDERS='vibe-build-reference-md vibe-build-vocab-data vibe-build-site-report-pages vibe-build-case-studies-index vibe-build-docs'

#: Everything under --out this script owns. Cleared on every build, so output that the
#: current corpus no longer justifies cannot survive into the new site.
readonly GENERATED_DIRS='data reference vocab reports case-studies docs'

#: Rendered here, not by a builder: they must exist whether or not there is any audit data.
readonly ALWAYS_RENDERED='dashboard.md featured-audits.md'

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)"
REPO_ROOT="$(dirname -- "$SCRIPT_DIR")"

usage() {
  echo "usage: site/build.sh --corpus <dir> --out <dir> [--skip-vitepress]" >&2
}

die_usage() {
  echo "site/build.sh: $1" >&2
  usage
  exit 2
}

absolute() {
  case "$1" in
    /*) printf '%s\n' "$1" ;;
    *) printf '%s\n' "$PWD/$1" ;;
  esac
}

CORPUS=''
OUT=''
SKIP_VITEPRESS=0

while [ "$#" -gt 0 ]; do
  case "$1" in
    --corpus)
      [ "$#" -ge 2 ] || die_usage "--corpus needs a directory"
      CORPUS="$2"; shift 2 ;;
    --out)
      [ "$#" -ge 2 ] || die_usage "--out needs a directory"
      OUT="$2"; shift 2 ;;
    --skip-vitepress) SKIP_VITEPRESS=1; shift ;;
    -h|--help) usage; exit 0 ;;
    *) die_usage "unknown argument: $1" ;;
  esac
done

[ -n "$CORPUS" ] || die_usage "--corpus is required"
[ -n "$OUT" ] || die_usage "--out is required"

CORPUS="$(absolute "$CORPUS")"
mkdir -p "$OUT"
OUT="$(cd -- "$OUT" && pwd -P)"

# An absent or empty corpus is the pre-migration state (D-C), not a failure.
CORPUS_POPULATED=0
if [ -d "$CORPUS" ] && [ -n "$(ls -A "$CORPUS" 2>/dev/null)" ]; then
  CORPUS_POPULATED=1
fi

STAGE="$(mktemp -d "${TMPDIR:-/tmp}/vibe-site-build.XXXXXX")"
cleanup() { rm -rf "$STAGE"; }
trap cleanup EXIT

echo "==> Building the site from $CORPUS into $OUT"

for builder in $BUILDERS; do
  path="$REPO_ROOT/bin/$builder"
  [ -f "$path" ] || { echo "site/build.sh: missing builder: $path" >&2; exit 1; }
  echo "--> $builder"
  python3 "$path" --corpus "$CORPUS" --out "$STAGE"
done

# The swap. Clear what this script owns first — a builder that legitimately emits nothing for
# the current corpus must still retire the previous build's directory — then move the staged
# tree in, replacing each top-level entry whole.
for dir in $GENERATED_DIRS; do
  rm -rf "${OUT:?}/$dir"
done
for staged in "$STAGE"/* "$STAGE"/.[!.]*; do
  [ -e "$staged" ] || continue
  name="$(basename -- "$staged")"
  rm -rf "${OUT:?}/$name"
  mv -- "$staged" "$OUT/$name"
done

# Write via a temp file in the destination directory, then mv: a reader never sees a
# half-written page.
render() {
  page="$1"
  tmp="$OUT/.$page.tmp.$$"
  cat >"$tmp"
  mv -- "$tmp" "$OUT/$page"
}

# Only link to a page that the build actually produced — the link check over the built output
# holds every relative target to resolving.
section_links() {
  for section in reference vocab reports case-studies docs; do
    if [ -f "$OUT/$section/index.md" ]; then
      echo "- [${section}](${section}/index.md)"
    fi
  done
}

featured_links() {
  found=0
  if [ -d "$OUT/reports" ]; then
    for report in "$OUT"/reports/*.md; do
      [ -e "$report" ] || continue
      name="$(basename -- "$report" .md)"
      [ "$name" = "index" ] && continue
      echo "- [${name}](reports/${name}.md)"
      found=1
    done
  fi
  [ "$found" -eq 1 ] || echo "- _No audit has been featured yet._"
}

if [ "$CORPUS_POPULATED" -eq 1 ]; then
  render dashboard.md <<EOF
# Dashboard

Generated by \`site/build.sh\` from the audit corpus.

## Sections

$(section_links)
EOF

  render featured-audits.md <<EOF
# Featured audits

The audits highlighted from the current corpus.

$(featured_links)
EOF
else
  render dashboard.md <<EOF
# Dashboard

$EMPTY_NOTICE — this checkout carries no audit corpus, so every panel below is empty by
design rather than broken. Run an audit and rebuild to populate it.

## Sections

$(section_links)
EOF

  render featured-audits.md <<EOF
# Featured audits

$EMPTY_NOTICE — no audit has been published, so there is nothing to feature. This page
returns as soon as the corpus carries its first audit.
EOF
fi

for page in $ALWAYS_RENDERED; do
  [ -f "$OUT/$page" ] || { echo "site/build.sh: failed to render $page" >&2; exit 1; }
done

if [ "$SKIP_VITEPRESS" -eq 1 ]; then
  echo "==> Skipping the VitePress build (--skip-vitepress)"
  echo "Built: $OUT"
  exit 0
fi

if [ ! -f "$SCRIPT_DIR/package.json" ]; then
  echo "site/build.sh: no $SCRIPT_DIR/package.json, so the VitePress build cannot run;" >&2
  echo "site/build.sh: pass --skip-vitepress to build the pages alone" >&2
  exit 1
fi

if [ "$OUT" != "$SCRIPT_DIR" ]; then
  echo "site/build.sh: note — VitePress builds $SCRIPT_DIR, while the pages were written to $OUT" >&2
fi

# Choose the package manager from the LOCKFILE, not from what happens to be installed. Picking
# pnpm merely because it is on PATH broke the build here: with no pnpm-lock.yaml, pnpm still
# resolved the tree but refused to run esbuild's install script (ERR_PNPM_IGNORED_BUILDS), so
# VitePress had no binary to invoke. The lockfile states which manager owns this project.
if [ -f "$SCRIPT_DIR/pnpm-lock.yaml" ] && command -v pnpm >/dev/null 2>&1; then
  PKG=pnpm
elif command -v npm >/dev/null 2>&1; then
  PKG=npm
elif command -v pnpm >/dev/null 2>&1; then
  PKG=pnpm
else
  echo "site/build.sh: neither pnpm nor npm is on PATH; pass --skip-vitepress" >&2
  exit 1
fi

echo "==> Installing site dependencies ($PKG)"
( cd "$SCRIPT_DIR" && "$PKG" install )
echo "==> Running the VitePress build ($PKG run build)"
( cd "$SCRIPT_DIR" && "$PKG" run build )

echo "Built: $OUT"
