#!/usr/bin/env python3
# SPDX-License-Identifier: ISC
"""Mirror-sync generator (E7.2 / vibe-54, F9.6).

Regenerates the Codex CLI mirror under ``codex/`` from four source sets and writes
``codex/MIRROR-MANIFEST.json`` — per-FILE records binding every mirror file to the exact
source bytes it was generated from, plus reasoned rows for everything deliberately not
mirrored. ``bin/vibe-check --mirrors`` is the independent reader.

Determinism is a contract (the acceptance says byte-identical): sorted iteration, no
timestamps, version read only from the plugin manifest, stable JSON.

Inventory comes from the PRODUCTION TABLES below. The only injection point is the
``sets=`` parameter of :func:`generate` — a Python-API seam for unit tests; the CLI is
unconditionally production-bound (no flag, no environment variable — pinned by
``tests/test_mirror_sync.py::ProductionBinding``).
"""

import argparse
import hashlib
import json
import re
import sys
from pathlib import Path

_HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(_HERE / "lib"))

import bridge  # noqa: E402  (the audited write primitive — vibe-94/vibe-103 discipline)

#: F9.6 set (a): the merge's 19 knowledge skills plus the post-merge additions `auditing`
#: (E4.1) and `roasting` (E4.3) — the 21-skill scope reading recorded in the vibe-54 plan.
KNOWLEDGE = (
    "agent-design", "auditing", "conventions", "conventions-antigravity",
    "conventions-claude", "conventions-codex", "orchestration", "patterns", "roasting",
    "rules", "scoring", "security", "testing", "vibe-core", "vocabulary",
    "writing-agents", "writing-hooks", "writing-plugins", "writing-prompts",
    "writing-rules", "writing-skills",
)
#: User-invocable workflow skills — outside set (a) by scope, not by portability.
WORKFLOW = ("issue2pr", "refine-proposal", "runs-stats")
#: F9.6 set (c): the six roast analysis agents.
ROAST_AGENTS = ("architecture", "edge-cases", "error-handling", "recon", "security",
                "testing")

#: Out-of-mirror destinations copied into the mirror (source → mirror), per the vibe-54
#: frozen analysis's dependency inventory.
COPIED_DEPS = {
    "schemas/audit-output.schema.json": "codex/schemas/audit-output.schema.json",
}
#: commands/shared partials copied under vibe-auditing (set-(a) links rewritten to them).
AUDITING_PARTIALS = ("classify", "discover")

#: Slash-command dispositions (frozen from the analysis's 16-command inventory): roast is
#: rewritten to its mirrored identity; every other command is kept literal under the banner
#: note. A command missing from this table is a generation error, never a silent pass.
SLASH_REWRITE = {"roast": "$vibe-roast"}
SLASH_LITERAL = (
    "advisor", "bridge", "check", "fix", "init", "issue2pr", "jobs", "nl-audit",
    "refine-proposal", "repair", "scan", "score", "security-scan", "test", "update",
)

BANNER = ("<!-- GENERATED by scripts/mirror-sync.py from {source} — do not edit. "
          "Slash commands refer to the Claude-side vibe-suite plugin; source paths refer "
          "to the vibe-suite repository. -->")

README_TEXT = """<!-- GENERATED by scripts/mirror-sync.py — do not edit. -->

# `codex/` — Codex CLI mirror — GENERATED

**Never hand-edit anything in this directory.** Its contents are generated from
the Claude-side artifacts by the mirror-sync generator; edits here are overwritten on the next
regeneration. Change the source artifact instead (set (d)'s sources live in `codex-src/`),
then run `python3 scripts/mirror-sync.py generate`.

`MIRROR-MANIFEST.json` binds every file here to its source bytes; `bin/vibe-check --mirrors`
fails on any drift in either direction.
"""


class MirrorError(Exception):
    pass


def sha256_file(path):
    return hashlib.sha256(Path(path).read_bytes()).hexdigest()


def _plugin_version(root):
    doc = json.loads((root / ".claude-plugin" / "plugin.json").read_text(encoding="utf-8"))
    return doc["version"]


def _split_frontmatter(text):
    if not text.startswith("---\n"):
        raise MirrorError("source lacks frontmatter")
    end = text.index("\n---", 4)
    fm = text[4:end]
    body = text[end + 4:]
    if body.startswith("\n"):
        body = body[1:]
    return fm, body


def _parse_fm(fm):
    keys = {}
    for line in fm.split("\n"):
        m = re.match(r"^([A-Za-z_-]+):\s*(.*)$", line)
        if m:
            keys[m.group(1)] = m.group(2).strip()
    return keys


_CLAUDE_ONLY_KEYS = ("model", "tools", "globs")


def _transform_markdown(text, *, source_rel, target_name, version, name_map,
                        in_auditing=False):
    """One deterministic pass; returns (new_text, dropped_keys).

    Files without frontmatter (sidecar markdown) get body transforms + the banner only —
    inventing a frontmatter block for a reference file would change its kind."""
    has_fm = text.startswith("---\n")
    if has_fm:
        fm, body = _split_frontmatter(text)
        keys = _parse_fm(fm)
        dropped = sorted(k for k in _CLAUDE_ONLY_KEYS if k in keys and k != "globs")
        description = keys.get("description", "")
        for cmd, repl in sorted(SLASH_REWRITE.items()):
            description = description.replace(f"/vibe-suite:{cmd}", repl)
        lines = [f"name: {target_name}",
                 f"description: {description}",
                 "metadata:",
                 f"  version: {version}"]
        if "globs" in keys:
            lines.append(f"  short-description: {keys['globs']}")
        new_fm = "\n".join(lines)
    else:
        body, dropped, new_fm = text, [], None

    body = body.replace("## [Agent: ", "## [Skill: ")
    body = body.replace("Bash Scope", "Shell Scope")

    # link rewrites: sibling skills, agent-shape links, auditing partial copies
    for src_name, mirror_name in sorted(name_map.items()):
        body = body.replace(f"(../{src_name}/", f"(../{mirror_name}/")
        body = body.replace(f"(../skills/{src_name}/", f"(../{mirror_name}/")
        body = body.replace(f"`../{src_name}/", f"`../{mirror_name}/")
        body = body.replace(f"`../skills/{src_name}/", f"`../{mirror_name}/")
    if in_auditing:
        for part in AUDITING_PARTIALS:
            body = body.replace(f"(../../commands/shared/{part}.md)",
                                f"(references/{part}.md)")

    # slash-command dispositions, with per-occurrence accounting (A-1)
    slash_counts = {}
    for m in re.findall(r"/vibe-suite:([a-z0-9-]+)", body):
        slash_counts[m] = slash_counts.get(m, 0) + 1
    for m in sorted(slash_counts):
        if m in SLASH_REWRITE:
            body = body.replace(f"/vibe-suite:{m}", SLASH_REWRITE[m])
        elif m not in SLASH_LITERAL:
            raise MirrorError(f"{source_rel}: unclassified slash reference "
                              f"/vibe-suite:{m} — extend the disposition table")

    banner = BANNER.format(source=source_rel)
    if new_fm is None:
        return f"{banner}\n\n{body}", dropped, slash_counts
    return f"---\n{new_fm}\n---\n\n{banner}\n\n{body}", dropped, slash_counts


def _roast_variant(version, roast_agents=ROAST_AGENTS, knowledge=KNOWLEDGE):
    """The `vibe-roast` sequential variant — the one semantic transform (plan D-f/A-3).
    Criteria live in the mirrored roasting skill; this variant owns flow, not definitions.
    The specialist roster and the criteria link render from the SETS so a fixture world
    stays internally consistent — production renders the six-agent roster."""
    specialists = ", ".join(f"$vibe-roast-{a}" for a in sorted(roast_agents)
                            if a not in ("recon", "edge-cases"))
    recon_line = ("1. Always run the $vibe-roast-recon survey first; its survey is injected "
                  "into every later\n   pass under a context heading with \"do not "
                  "re-discover: this survey is the repository's\n   shape\". Prior "
                  "`vibe-report-*.md` files are excluded from every pass."
                  if "recon" in roast_agents else
                  "1. Prior `vibe-report-*.md` files are excluded from every pass.")
    edge = ("; styles 5–6 add\n$vibe-roast-edge-cases" if "edge-cases" in roast_agents
            else "")
    criteria = ("**Load the criteria first.** The dimensions (nine full, five mini), the six "
                "styles and the\neight add-ons are DEFINED by "
                "[$vibe-roasting](../vibe-roasting/SKILL.md) — read it before any\npass; "
                "this skill owns arguments, sequencing and the report only."
                if "roasting" in knowledge else
                "This skill owns arguments, sequencing and the report.")
    return f"""---
name: vibe-roast
description: Interrogate a codebase sequentially — a recon survey, specialist passes by style, then synthesis, an executive summary and a phased fixing plan written to a report.
metadata:
  version: {version}
---

{BANNER.format(source='commands/roast.md')}

# vibe-roast — sequential code interrogation

The Codex-native rendering of the roast flow: one lane, sequential skill passes, the same
report contract. The source command's multi-lane machinery does not exist here — this
runtime IS the single engine, so nothing needs selecting or cross-checking between lanes.

{criteria}

## Scope

Resolve the target with the scope grammar: an empty scope means uncommitted changes
(`git diff HEAD --name-only`); `staged` means staged changes (`git diff --cached
--name-only`); `commit -N` means the last N commits (`git diff HEAD~N --name-only`); an
explicit path is read from the filesystem without git. Enforce configured skip patterns from
the project's `.vibe-suite.md`. An empty resolved list stops with "No changes detected in
scope. Nothing to review." A trivial resolved set — formatting-only or comment-only changes —
asks for confirmation before a full interrogation is spent on it.

## Styles and depth

`--style 1-6` (default 2), meanings per the roasting criteria:

1. Architecture Review + Rewrite Plan — structure first; the plan proposes a target shape.
2. Hard-Nosed Critique + Roadmap — severity-ordered, blunt, with a sequenced roadmap.
3. Multi-Perspective Panel — the same findings argued from several stances, disagreements kept.
4. ADR Style — findings recast as decisions with context, options and consequences.
5. Paranoid Mode — adds the edge-cases pass; assumes hostile input and unlucky timing.
6. Select All — every style's closing sections in one report.

Styles 1–4 run the specialist roster ({specialists}){edge}.
Style 6 on more than 500 files stops and asks before any pass,
stating the file count and what Select All costs. Depth: `--mini` (five dimensions) or
`--full` (nine, test files included) — per the roasting criteria.

## Sequential passes

{recon_line}
2. Run each style-selected specialist skill in order, one at a time, feeding it the recon
   survey. More than 20 files: batch in groups of 10, one sequential pass per group,
   findings merged.
3. A specialist pass that fails records the gap in the report's coverage section and the run
   continues — a partial interrogation that says so beats a silent one.
4. Add-ons run after the specialists, sequentially, any subset of the eight from the
   roasting criteria — Scale stress, Hidden costs, Principle violations, Strangler fig,
   Success metrics, Before/after diagram, Assumptions audit, Compact & optimize — each
   appending one section, none replacing a dimension.

## Synthesis and report

Assign finding ids, synthesize across passes, write the executive summary and the phased
fixing plan, then write ONE report file with frontmatter `target`, `engine: codex`,
`style`, `generated`, `version`.
"""


def _agent_to_skill(text, *, agent_name, version, name_map):
    fm, body = _split_frontmatter(text)
    keys = _parse_fm(fm)
    dropped = sorted(k for k in _CLAUDE_ONLY_KEYS if k in keys)
    body = body.replace("## [Agent: ", "## [Skill: ")
    body = body.replace("Bash Scope", "Shell Scope")
    for src_name, mirror_name in sorted(name_map.items()):
        body = body.replace(f"(../skills/{src_name}/", f"(../{mirror_name}/")
        body = body.replace(f"`../skills/{src_name}/", f"`../{mirror_name}/")
    banner = BANNER.format(source=f"agents/{agent_name}.md")
    fm_out = (f"name: vibe-roast-{agent_name}\ndescription: {keys.get('description', '')}\n"
              f"metadata:\n  version: {version}")
    return f"---\n{fm_out}\n---\n\n{banner}\n\n{body}", dropped


def _default_sets(root):
    return {
        "knowledge": KNOWLEDGE,
        "workflow": WORKFLOW,
        "roast_agents": ROAST_AGENTS,
        "copied_deps": COPIED_DEPS,
        "auditing_partials": AUDITING_PARTIALS,
    }


def generate(root, sets=None):
    """Three phases (step-8 atomicity finding): RENDER everything in memory — every source
    read, every transform applied, every record computed — then VALIDATE the rendered set
    (link integrity, slash accounting), and only then SWAP the codex/ tree, restoring the
    previous bytes if any write fails. A failure in the first two phases leaves the
    committed tree untouched."""
    root = Path(root)
    s = sets or _default_sets(root)
    version = _plugin_version(root)

    outputs = {}          # mirror rel -> bytes
    records, out_of_scope, exclusions = [], [], []
    slash_totals = {}     # source rel -> {command: count}

    def render(dest_rel, data):
        if dest_rel in outputs:
            raise MirrorError(f"mirror path collision: {dest_rel}")
        outputs[dest_rel] = data.encode("utf-8") if isinstance(data, str) else data

    def record(source_rel, mirror_rel, transform, dropped=()):
        records.append({
            "source": source_rel, "mirror": mirror_rel, "transform": transform,
            "source_sha256": sha256_file(root / source_rel),
            "mirror_sha256": hashlib.sha256(outputs[mirror_rel]).hexdigest(),
            "dropped_keys": sorted(dropped),
        })

    def transform(src_path, source_rel, target_name, in_auditing=False):
        text, dropped, counts = _transform_markdown(
            src_path.read_text(encoding="utf-8"), source_rel=source_rel,
            target_name=target_name, version=version, name_map=name_map,
            in_auditing=in_auditing)
        if counts:
            slash_totals[source_rel] = dict(sorted(counts.items()))
        return text, dropped

    name_map = {k: f"vibe-{k}" for k in s["knowledge"]}

    # ---- phase 1: render -----------------------------------------------------------------
    for skill in sorted(s["knowledge"]):
        src_dir = root / "skills" / skill
        if not src_dir.is_dir():
            raise MirrorError(f"knowledge skill missing on disk: skills/{skill}/")
        for f in sorted(src_dir.rglob("*")):
            if not f.is_file():
                continue
            rel = f.relative_to(src_dir).as_posix()
            src_rel = f"skills/{skill}/{rel}"
            dst_rel = f"codex/skills/vibe-{skill}/{rel}"
            if f.suffix == ".md":
                text, dropped = transform(
                    f, src_rel,
                    f"vibe-{skill}" if rel == "SKILL.md" else Path(rel).stem,
                    in_auditing=(skill == "auditing"))
                render(dst_rel, text)
                record(src_rel, dst_rel, "markdown", dropped)
            else:
                render(dst_rel, f.read_bytes())
                record(src_rel, dst_rel, "verbatim")

    for part in sorted(s.get("auditing_partials", ())):
        src = root / "commands" / "shared" / f"{part}.md"
        if not src.is_file():
            continue
        src_rel = f"commands/shared/{part}.md"
        dst_rel = f"codex/skills/vibe-auditing/references/{part}.md"
        text, dropped = transform(src, src_rel, part)
        render(dst_rel, text)
        record(src_rel, dst_rel, "markdown", dropped)

    for src_rel, dst_rel in sorted(s["copied_deps"].items()):
        src = root / src_rel
        if not src.is_file():
            raise MirrorError(f"copied dependency missing on disk: {src_rel}")
        render(dst_rel, src.read_bytes())
        record(src_rel, dst_rel, "verbatim")

    if (root / "commands" / "roast.md").is_file():
        render("codex/skills/vibe-roast/SKILL.md",
               _roast_variant(version, tuple(s["roast_agents"]),
                              tuple(s["knowledge"])))
        record("commands/roast.md", "codex/skills/vibe-roast/SKILL.md", "variant")
        for part in ("scope-parse", "model-selection", "fallback"):
            exclusions.append({
                "source": f"commands/shared/{part}.md", "set": "b",
                "reason": ("scope grammar inlined into the vibe-roast variant"
                           if part == "scope-parse" else
                           "engine-selection machinery — collapsed to the single native "
                           "lane in the sequential variant"),
            })

    for agent in sorted(s["roast_agents"]):
        src = root / "agents" / f"{agent}.md"
        if not src.is_file():
            raise MirrorError(f"roast agent missing on disk: agents/{agent}.md")
        text, dropped = _agent_to_skill(src.read_text(encoding="utf-8"),
                                        agent_name=agent, version=version,
                                        name_map=name_map)
        dst_rel = f"codex/skills/vibe-roast-{agent}/SKILL.md"
        render(dst_rel, text)
        record(f"agents/{agent}.md", dst_rel, "markdown", dropped)

    codex_src = root / "codex-src"
    if codex_src.is_dir():
        for d in sorted(p for p in codex_src.iterdir() if p.is_dir()):
            for f in sorted(d.rglob("*")):
                if not f.is_file():
                    continue
                rel = f.relative_to(d).as_posix()
                src_rel = f"codex-src/{d.name}/{rel}"
                dst_rel = f"codex/skills/{d.name}/{rel}"
                if f.suffix == ".md":
                    text, dropped = transform(
                        f, src_rel, d.name if rel == "SKILL.md" else Path(rel).stem)
                    render(dst_rel, text)
                    record(src_rel, dst_rel, "markdown", dropped)
                else:
                    render(dst_rel, f.read_bytes())
                    record(src_rel, dst_rel, "verbatim")

    for wf in sorted(s["workflow"]):
        out_of_scope.append({
            "source": f"skills/{wf}/", "set": "a",
            "reason": "user-invocable workflow skill — outside F9.6 set (a)",
        })

    render("codex/README.md", README_TEXT)
    record(".claude-plugin/plugin.json", "codex/README.md", "generated")

    manifest = {
        "schema": 1,
        "plugin_version": version,
        "generator": "scripts/mirror-sync.py",
        "sets": {
            "knowledge": sorted(s["knowledge"]),
            "workflow": sorted(s["workflow"]),
            "roast_agents": sorted(s["roast_agents"]),
            "copied_deps": dict(sorted(s["copied_deps"].items())),
        },
        "records": sorted(records, key=lambda r: (r["mirror"], r["source"])),
        "out_of_scope": sorted(out_of_scope, key=lambda r: r["source"]),
        "exclusions": sorted(exclusions, key=lambda r: r["source"]),
        "transform_notes": {
            "slash_literal": sorted(SLASH_LITERAL),
            "slash_rewritten": sorted(SLASH_REWRITE),
            "slash_occurrences": {k: slash_totals[k] for k in sorted(slash_totals)},
            "globs_rule": "globs maps to metadata.short-description (no live source carries "
                          "globs today; proven on a synthetic fixture)",
        },
    }
    render("codex/MIRROR-MANIFEST.json",
           json.dumps(manifest, indent=2, sort_keys=True) + "\n")

    # ---- phase 2: validate the rendered set ----------------------------------------------
    problems = _validate_rendered(outputs)
    if problems:
        raise MirrorError("rendered tree failed validation: " + "; ".join(problems[:10]))

    # ---- phase 3: swap, with rollback ----------------------------------------------------
    previous = {}
    codex = root / "codex"
    if codex.exists():
        for f in sorted(codex.rglob("*")):
            if f.is_file():
                previous[f.relative_to(root).as_posix()] = f.read_bytes()
        bridge.remove_tree_at(root, "codex")
    try:
        for dest_rel in sorted(outputs):
            bridge.ensure_dir_at(root, str(Path(dest_rel).parent))
            bridge.publish_new(root, root / dest_rel, outputs[dest_rel])
    except Exception:
        # restore the previous tree byte-for-byte before re-raising
        if codex.exists():
            bridge.remove_tree_at(root, "codex")
        for dest_rel in sorted(previous):
            bridge.ensure_dir_at(root, str(Path(dest_rel).parent))
            bridge.publish_new(root, root / dest_rel, previous[dest_rel])
        raise
    return manifest


def _validate_rendered(outputs):
    """A-1's walker over the RENDERED set: every relative markdown link must resolve inside
    it (or into the repo above codex/), every surviving slash command must be classified,
    and every $vibe-* skill reference must name a rendered skill."""
    problems = []
    dirs = {str(Path(p).parent) for p in outputs} | {"codex", "codex/skills"}
    skills = {Path(p).parts[2] for p in outputs
              if len(Path(p).parts) > 3 and Path(p).parts[1] == "skills"}
    for rel, data in sorted(outputs.items()):
        if not rel.endswith(".md"):
            continue
        text = data.decode("utf-8", errors="replace")
        base = Path(rel).parent
        for m in re.finditer(r"\]\((\.\.?/[^)#\s]+)", text):
            target = (base / m.group(1))
            norm = Path(*[p for p in target.parts if p != "."])
            parts = []
            for part in norm.parts:
                if part == "..":
                    if parts:
                        parts.pop()
                    else:
                        parts = None
                        break
                else:
                    parts.append(part)
            if parts is None:
                continue  # points above codex/ into the repo — the repo has it
            resolved = "/".join(parts)
            if resolved not in outputs and resolved not in dirs \
                    and not any(k.startswith(resolved + "/") for k in outputs):
                problems.append(f"{rel}: dangling link {m.group(1)}")
        for m in set(re.findall(r"/vibe-suite:([a-z0-9-]+)", text)):
            if m not in SLASH_LITERAL:
                problems.append(f"{rel}: unclassified surviving slash command {m}")
        for m in set(re.findall(r"\$vibe-([a-z0-9-]+)", text)):
            if f"vibe-{m}" not in skills:
                problems.append(f"{rel}: $vibe-{m} names no rendered skill")
    return problems


def check_links(codex_root):
    """Walk relative links in the generated tree; return unresolved ones."""
    codex_root = Path(codex_root)
    problems = []
    for f in sorted(codex_root.rglob("*.md")):
        text = f.read_text(encoding="utf-8", errors="replace")
        for m in re.finditer(r"\]\((\.\.?/[^)#\s]+)", text):
            target = (f.parent / m.group(1)).resolve()
            base = codex_root.parent.resolve()
            if not target.exists() or base not in target.parents and target != base:
                if not target.exists():
                    problems.append(f"{f}: dangling link {m.group(1)}")
    return problems


def main(argv=None):
    parser = argparse.ArgumentParser(prog="mirror-sync")
    parser.add_argument("command", choices=["generate"])
    parser.add_argument("--root", default=".")
    args = parser.parse_args(argv)
    try:
        manifest = generate(Path(args.root))
    except MirrorError as exc:
        print(f"mirror-sync: {exc}", file=sys.stderr)
        return 1
    print(f"mirror-sync: {len(manifest['records'])} records, "
          f"{len(manifest['out_of_scope'])} out-of-scope, "
          f"{len(manifest['exclusions'])} exclusions")
    return 0


if __name__ == "__main__":
    sys.exit(main())
