#!/usr/bin/env python3
# SPDX-License-Identifier: ISC
"""Render and publish an issue2pr profile and its pointer (E5.5 / vibe-44).

    write_profile.py --root <dir> --fields <file|-> [--force]

**Everything that can fail happens before anything is published.** `bridge.write_atomic` makes each
*file* atomic; it does not make profile-plus-pointer atomic, and the gap between two writes is where a
half-finished state lives. So: pin the root before any *read*, preflight both destinations, render the
profile and **lint the candidate in memory** — a profile that would not pass is never written at all —
and only then write, profile first.

Profile first because a pointer to a missing profile is a worse residue than a profile nothing points
at. If the pointer write fails the orphaned profile is **named**, not silently left: rolling it back
would delete a file the user may want, and saying nothing is worse than either. The residue is bounded
and described, which is achievable; a two-file transaction is not.

**Repository-controlled strings are refused, not escaped.** Gate commands come from files and interview
answers come from people, and the profile is read back by `profile_lint.py`'s **closed** grammar —
balanced quotes, two-space indentation, no multi-line scalars, no escaping convention. Inventing an
escaping scheme its parser does not implement would produce a file that renders and will not read back.
"""

import argparse
import json
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
sys.path.insert(0, str(HERE / "lib"))

import bridge  # noqa: E402
import profile_lint  # noqa: E402

EXIT_OK, EXIT_BAD_INPUT, EXIT_GUARD, EXIT_INVALID, EXIT_WRITE_FAILED = 0, 1, 2, 3, 4

POINTER = ".vibe-suite.md"

#: Characters the lint's grammar cannot carry. Refused with the value named, so the user can fix the
#: source rather than wonder which field was rejected.
UNRENDERABLE = re.compile(r"[\n\r\t\x00-\x08\x0b\x0c\x0e-\x1f]")

NOT_ASKED_NOTE = """
## Round bounds

floor 2, ceiling 5, default 2 — the pipeline's own, not this profile's. The cap is a **per-run** flag
(`--max-review-rounds`), which is why `profile init` did not ask for it: there is no field here for the
answer to live in, and a profile carrying one would be rejected as an unknown field.

## Two questions `profile init` did not ask

Recorded so their absence is a decision rather than a gap.

- **The review-iteration cap** — per-run, as above.
- **The reviewer backend** — `reviewer_backend`'s domain is `codex` alone, so omitting the field
  selects exactly what the only legal answer would have selected.

Both were narrowed by an amendment to the issue that specified them. If a contract field for the cap
appears, or a second backend, this is the decision to revisit.
"""


def unrenderable(fields):
    """Every value the closed grammar cannot carry, named with its field."""
    problems = []
    for name, value in sorted(fields.items()):
        for item in (value if isinstance(value, list) else [value]):
            if not isinstance(item, str):
                continue
            if UNRENDERABLE.search(item):
                problems.append("%s: contains a newline or control character, which the profile "
                                "grammar cannot carry" % name)
            elif item.count("'") % 2 or item.count('"') % 2:
                problems.append("%s: contains an unbalanced quote, and the grammar has no escaping "
                                "convention" % name)
    return problems


def render(fields):
    """The profile, in the subset `profile_lint.parse_frontmatter` accepts."""
    lines = ["---"]
    for name in ("contract_version", "project_id", "repo_id", "repo_path", "base_branch",
                 "source_driver", "id_pattern", "url_regex", "branch_template"):
        value = fields[name]
        lines.append("%s: %s" % (name, value if name == "contract_version" else "'%s'" % value))
    lines.append("gates:")
    for gate in fields["gates"]:
        lines.append("  - '%s'" % gate)
    lines.append("---")
    lines.append("")
    lines.append("# %s" % fields["project_id"])
    lines.append("")
    lines.append("Generated by `/vibe-suite:issue2pr profile init`. Every value above was detected "
                 "from the repository")
    lines.append("or supplied in the interview; nothing was guessed.")
    if not fields["gates"]:
        lines.append("")
        lines.append("**No gates were detected.** `gates` is empty rather than guessed, because a "
                     "guessed gate is a command")
        lines.append("the pipeline will run. Add the commands that must pass before a PR opens.")
    lines.append(NOT_ASKED_NOTE)
    return "\n".join(lines) + "\n"


def read_pointer(path):
    """The existing configuration, or a fresh empty one. Never discarded."""
    if not path.is_file():
        return "---\n---\n"
    return path.read_text(encoding="utf-8")


def set_pointer(text, profile_id):
    """Set or replace `issue2pr_profile`, preserving every other key and the body byte for byte."""
    if not text.startswith("---"):
        return "---\nissue2pr_profile: %s\n---\n\n%s" % (profile_id, text)
    end = text.find("\n---", 3)
    if end == -1:
        return "---\nissue2pr_profile: %s\n---\n\n%s" % (profile_id, text)
    head, tail = text[4:end], text[end:]
    lines = [l for l in head.splitlines() if not re.match(r"^issue2pr_profile:", l)]
    lines.append("issue2pr_profile: %s" % profile_id)
    return "---\n" + "\n".join(l for l in lines if l.strip() or True) + tail


def main(argv=None):
    parser = argparse.ArgumentParser(description="Render and publish a profile and its pointer.")
    parser.add_argument("--root", required=True)
    parser.add_argument("--fields", required=True)
    parser.add_argument("--force", action="store_true")
    args = parser.parse_args(argv)

    raw = sys.stdin.read() if args.fields == "-" else Path(args.fields).read_text(encoding="utf-8")
    try:
        fields = json.loads(raw)
    except ValueError as exc:
        print("write_profile: %s" % exc, file=sys.stderr)
        return EXIT_BAD_INPUT

    # 1. Pin before reading, not merely before writing.
    root = Path(args.root).absolute()
    try:
        bridge.assert_root(root)
        bridge.pin_root(root)
    except bridge.BridgeError as exc:
        print("write_profile: %s" % exc, file=sys.stderr)
        return EXIT_GUARD

    problems = unrenderable(fields)
    if problems:
        print("write_profile: %d value(s) the profile grammar cannot carry:" % len(problems),
              file=sys.stderr)
        for problem in problems:
            print("  - %s" % problem, file=sys.stderr)
        return EXIT_INVALID

    profile_id = fields.get("profile_id")
    if not profile_id or not re.fullmatch(r"[a-z0-9][a-z0-9-]*", profile_id):
        print("write_profile: %r is not a usable profile id" % profile_id, file=sys.stderr)
        return EXIT_BAD_INPUT

    # 2. Preflight BOTH destinations before either is touched.
    profile_path = root / "profiles" / ("%s.md" % profile_id)
    pointer_path = root / POINTER
    for path, label in ((profile_path, "profile"), (pointer_path, "pointer")):
        if path.is_symlink():
            print("write_profile: refusing to follow a symlinked %s at %s" % (label, path),
                  file=sys.stderr)
            return EXIT_GUARD
    if profile_path.exists() and not args.force:
        print("write_profile: %s already exists; pass --force to replace it" % profile_path,
              file=sys.stderr)
        return EXIT_GUARD

    existing = read_pointer(pointer_path)
    current = re.search(r"(?m)^issue2pr_profile:\s*(\S+)\s*$", existing)
    if current and current.group(1) != profile_id and not args.force:
        print("write_profile: %s already points at %r; pass --force to repoint it"
              % (POINTER, current.group(1)), file=sys.stderr)
        return EXIT_GUARD

    # 3. Render and lint the candidate BEFORE publishing anything.
    document = render(fields)
    errors = profile_lint.validate_text(document, root, structural=False) \
        if hasattr(profile_lint, "validate_text") else None
    if errors:
        print("write_profile: the generated profile would not pass its own lint:", file=sys.stderr)
        for error in errors:
            print("  - %s" % error, file=sys.stderr)
        return EXIT_INVALID

    # 4. Profile first — a pointer to a missing profile is the worse residue.
    profile_path.parent.mkdir(parents=True, exist_ok=True)
    try:
        bridge.write_atomic(root, profile_path, document)
    except (bridge.BridgeError, ValueError) as exc:
        print("write_profile: refusing to write %s: %s" % (profile_path, exc), file=sys.stderr)
        return EXIT_WRITE_FAILED

    try:
        bridge.write_atomic(root, pointer_path, set_pointer(existing, profile_id))
    except (bridge.BridgeError, ValueError) as exc:
        # 5. Name the residue rather than leaving it to be discovered.
        print("write_profile: wrote %s but could not update %s (%s).\n"
              "  The profile exists and nothing points at it. Add "
              "`issue2pr_profile: %s` by hand, or re-run with --force."
              % (profile_path, pointer_path, exc, profile_id), file=sys.stderr)
        return EXIT_WRITE_FAILED

    print("write_profile: wrote %s and pointed %s at %s" % (profile_path, POINTER, profile_id))
    return EXIT_OK


if __name__ == "__main__":
    sys.exit(main())
