#!/usr/bin/env python3
# SPDX-License-Identifier: ISC
"""AC-1 merge-completeness check: every source artifact is claimed by `docs/disposition.yaml`.

§6 of the merge proposal maps every source function to where it landed in vibe-suite. This is the
disk-driven check that keeps that map honest — "so an artifact missing from this map fails the build
rather than passing silently".

Four things make it a real check rather than a self-referential one.

**Coverage is bidirectional.** Every allowlisted path must be claimed exactly once, *and* every
claimed path must exist and be allowlisted. A stale row naming a path that no longer exists is
exactly as damaging as a missing row, because either way the map has stopped describing the trees.

**The §6 row inventory is a constant here, not derived from the file being checked.** Otherwise
deleting a row would delete its own test, and a row claiming no allowlisted path — a `D` row — could
vanish unnoticed. AC-1 calls this out by name: "disk-driven, not self-referential".

**The pins are constants here too.** Comparing a manifest's commit to `disposition.yaml`'s commit
proves only that two editable files agree; both can be changed to the same wrong value. Re-pinning
must be a code change.

**The allowlist and exclusion list are transcribed from AC-1, and exist once.** They are applied
here and nowhere else — the manifests are unfiltered on purpose.
"""

import argparse
import json
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent

# --------------------------------------------------------------------------- pins
# Full commits for the short forms the issue names. Constants, so re-pinning is reviewable.
PINS = {
    "cc-suite":         "bb605ec4",
    "grill-for-claude": "938b1e83",
    "nlpm":             "4ef75d4a",
}

# --------------------------------------------------------------------------- AC-1's two lists
# Transcribed from §10 AC-1. This is the single definition; nothing else filters.
ALLOWLIST = (
    "commands/**/*.md",
    "agents/**/*.md",
    "skills/**/SKILL.md",          # source skills nest one level deeper in cc-suite and nlpm
    "hooks/**",
    "scripts/**/*",                # including nested libraries, e.g. scripts/lib/*.mjs
    "auditor/scripts/**/*",
    "bin/*",
    ".github/workflows/**",        # "workflows"
    "templates/**",
    "prompts/**",
    "schemas/**",
    ".claude-plugin/**",
    ".codex-plugin/**",
    "codex/**",                    # codex-mirror trees, incl. AGENTS files
    "site/**",
    "README.md", "CLAUDE.md", "AGENTS.md", "GEMINI.md", "PRIVACY.md", "package.json",
)

#: Directory names excluded wherever they appear as a path component.
EXCLUDED_DIRS = (".git", "__pycache__", "node_modules")

#: ".DS_Store and other OS junk", pinned to exact basenames.
OS_JUNK = (".DS_Store", "Thumbs.db", "desktop.ini", ".Spotlight-V100", ".Trashes")

#: "generated reports" — regenerated by tooling rather than authored.
GENERATED_REPORTS = ("auditor/reports/**", "nlpm-badge.json")

#: "the §7A row-9 migrated ops data" — the corpora the migration tool publishes.
ROW9_OPS_DATA = (
    "auditor/reports/**", "auditor/exemplars/**", "auditor/audits/**", "auditor/logs/**",
    "auditor/findings.jsonl", "auditor/disagreements.jsonl", "auditor/vocab-advisories.jsonl",
    "case-studies/**",
)
# auditor/reports/** is excluded by two routes deliberately: removing either must not un-exclude it.

# --------------------------------------------------------------------------- expected counts
SKILL_COUNTS = {"cc-suite": 13, "nlpm": 17}
NESTED_SCRIPT_LIB_COUNTS = {("cc-suite", "scripts/lib/**"): 7, ("nlpm", "auditor/scripts/**"): 32}

#: §5 counts 12 workspace-skill resources, all roamex-era. The live trees hold 14: `issue2pr` gained
#: `profiles/vibe-suite.md` and `templates/vibe-suite-pr-body.md` for this project after the proposal
#: was written. 12 = 14 - 2. Asserted because AC-1 wants a count that fails loudly, and honest
#: because the difference is accounted for rather than absorbed.
WORKSPACE_RESOURCE_COUNT = 14
WORKSPACE_ROOTS = (".claude/skills/issue2pr", ".claude/skills/refine-proposal",
                   ".claude/skills/runs-stats")

DISPOSITIONS = frozenset("KMRGD")
_TARGET = re.compile(r"F[0-9]+\.[0-9]+$")


class CoverageError(Exception):
    """A failure that must fail CI."""


# --------------------------------------------------------------------------- glob
def _translate(pattern):
    """Anchored glob → regex.

    `fnmatch` is not usable here: its `*` crosses `/`, which would make `scripts/**/*` and
    `commands/**/*.md` mean something other than what AC-1's text says. The four tokens below are
    the whole language.
    """
    out, index = ["^"], 0
    while index < len(pattern):
        if pattern.startswith("**/", index):
            out.append("(?:[^/]+/)*"); index += 3
        elif pattern.startswith("**", index):
            out.append(".*"); index += 2
        elif pattern[index] == "*":
            out.append("[^/]*"); index += 1
        elif pattern[index] == "?":
            out.append("[^/]"); index += 1
        else:
            out.append(re.escape(pattern[index])); index += 1
    out.append("$")
    return re.compile("".join(out))


_CACHE = {}


def matches(path, pattern):
    if pattern not in _CACHE:
        _CACHE[pattern] = _translate(pattern)
    return _CACHE[pattern].match(path) is not None


def matches_any(path, patterns):
    return any(matches(path, pattern) for pattern in patterns)


def is_excluded(path):
    parts = path.split("/")
    if any(part in EXCLUDED_DIRS for part in parts):
        return True
    base = parts[-1]
    if base in OS_JUNK or base.startswith("._"):
        return True
    return matches_any(path, GENERATED_REPORTS) or matches_any(path, ROW9_OPS_DATA)


def is_allowlisted(path):
    return matches_any(path, ALLOWLIST) and not is_excluded(path)
