#!/usr/bin/env python3
# SPDX-License-Identifier: ISC
"""Generate the exemplar gallery index from the exemplar corpus.

Walks `<data-dir>/exemplars/*.md`, reads each file's frontmatter, and writes `README.md` with
three views of the same set: by rule, by score, by repo.

DETERMINISM IS THE CONTRACT. The gallery is regenerated after every exemplar write and checked
in CI with `--check`, so output must depend only on the corpus CONTENT, never on the order the
filesystem happens to return entries in. Preserving input order produces a gallery that is
correct, complete, and different on every machine — so `--check` reports drift on an unchanged
corpus, the freshness gate cries wolf, and people learn to ignore it. Every view is sorted on an
explicit key, with a tie-breaker, so two runs on the same corpus are byte-identical.

Frontmatter is parsed with the stdlib. This repository ships no YAML dependency, and a helper
that silently degrades when one is missing would leave the gallery permanently stale.

Malformed exemplars are skipped rather than fatal: the gallery is an index, not a validator, and
`validate-rule-ids.py` owns strictness. Skips are counted and reported so a corpus quietly
failing to parse is visible.

Exit codes:
  0  gallery written, or unchanged under --check
  1  gallery would change (--check only)
  2  the corpus directory is missing under --check
"""
from __future__ import annotations

import argparse
import os
import re
import sys
from collections import defaultdict
from pathlib import Path

FRONTMATTER = re.compile(r"\A---[ \t]*\n(.*?)\n---[ \t]*(?:\n|\Z)", re.DOTALL)
RULE = re.compile(r"^[ \t]+-[ \t]+(R\d{2})\b")
SCALARS = ("slug", "repo", "audited", "commit_sha", "score")


def parse_frontmatter(text):
    """The frontmatter fields this gallery needs. `{}` when there is no frontmatter."""
    found = FRONTMATTER.match(text)
    if not found:
        return {}
    block = found.group(1)
    out = {}
    for key in SCALARS:
        m = re.search(rf"^{key}:[ \t]*(\S+)", block, re.MULTILINE)
        if m:
            out[key] = m.group(1).strip().strip("\"'")
    # BOTH shapes the exemplar workflow accepts: a bracketed inline sequence and a block list.
    # It documents both and refuses a bare string, so recognising only the block form drops
    # every inline exemplar from the gallery — silently, since a gallery missing entries still
    # renders and reads as "no exemplar demonstrates this rule".
    inline = re.search(r"^exemplifies:[ \t]*\[(.*?)\][ \t]*$", block, re.MULTILINE)
    if inline:
        rules = re.findall(r"[A-Za-z0-9:_-]+", inline.group(1))
    else:
        rules, in_list = [], False
        for line in block.splitlines():
            if re.match(r"^exemplifies:[ \t]*$", line):
                in_list = True
                continue
            if not in_list:
                continue
            m = RULE.match(line)
            if m:
                rules.append(m.group(1))
            elif line and not line[0].isspace():
                in_list = False          # a new top-level key ends the list
    out["exemplifies"] = rules
    return out


def load_exemplars(directory):
    """Every parseable exemplar, plus a count of those skipped."""
    directory = Path(directory)
    if not directory.is_dir():
        return [], 0
    items, skipped = [], 0
    for path in sorted(directory.glob("*.md")):
        if path.name == "README.md":
            continue
        try:
            front = parse_frontmatter(path.read_text(encoding="utf-8", errors="replace"))
        except OSError:
            skipped += 1
            continue
        if not front.get("repo"):
            skipped += 1                 # no repo: nothing to index it under
            continue
        try:
            score = int(front.get("score", ""))
        except (TypeError, ValueError):
            score = None
        items.append({
            "slug": front.get("slug") or path.stem,
            "repo": front["repo"],
            "audited": front.get("audited", ""),
            "score": score,
            "rules": sorted(set(front.get("exemplifies") or [])),
            "file": path.name,
        })
    return items, skipped


def render(items):
    """The gallery, as text. Sorted on explicit keys so reruns are byte-identical."""
    lines = ["# Exemplar gallery", "",
             f"{len(items)} exemplar(s). Generated by `auditor/scripts/build-exemplar-gallery.py`"
             " — edit the exemplars, not this file.", ""]

    lines += ["## By rule", ""]
    by_rule = defaultdict(list)
    for item in items:
        for rule in item["rules"]:
            by_rule[rule].append(item)
    for rule in sorted(by_rule):
        lines.append(f"### {rule}")
        for item in sorted(by_rule[rule], key=lambda i: (i["repo"], i["slug"])):
            lines.append(f"- [{item['repo']}]({item['file']})")
        lines.append("")

    lines += ["## By score", ""]
    # Highest first; unscored last. Tie-break on repo so equal scores never reorder.
    ordered = sorted(items, key=lambda i: (i["score"] is None,
                                           -(i["score"] or 0), i["repo"], i["slug"]))
    for item in ordered:
        score = "—" if item["score"] is None else f"{item['score']}/100"
        lines.append(f"- {score} — [{item['repo']}]({item['file']})")
    lines.append("")

    lines += ["## By repo", ""]
    for item in sorted(items, key=lambda i: (i["repo"], i["slug"])):
        rules = ", ".join(item["rules"]) or "—"
        lines.append(f"- [{item['repo']}]({item['file']}) — {rules}")
    lines.append("")
    return "\n".join(lines)


def main(argv=None):
    parser = argparse.ArgumentParser(description="Build the exemplar gallery index.")
    parser.add_argument("--data-dir", default=os.environ.get("AUDITOR_DATA_DIR", "."))
    parser.add_argument("--exemplars-dir", default=None)
    parser.add_argument("--output", default=None)
    parser.add_argument("--check", action="store_true",
                        help="exit 1 if the gallery on disk differs from what would be written")
    args = parser.parse_args(argv)

    exemplars = Path(args.exemplars_dir or Path(args.data_dir) / "exemplars")
    output = Path(args.output or exemplars / "README.md")

    if args.check and not exemplars.is_dir():
        print(f"REFUSE:build-exemplar-gallery:corpus-missing {exemplars}", file=sys.stderr)
        return 2

    items, skipped = load_exemplars(exemplars)
    if skipped:
        print(f"build-exemplar-gallery: skipped {skipped} unparseable exemplar(s)",
              file=sys.stderr)
    text = render(items)

    if args.check:
        current = output.read_text(encoding="utf-8") if output.is_file() else None
        if current == text:
            return 0
        print("build-exemplar-gallery: gallery is stale; regenerate it", file=sys.stderr)
        return 1

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(text, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
